name: Generate Profile Summary Cards

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user: singhsumit880
          theme: github_dark